spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/data6?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 5743
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: kt33439312@gmail.com
    password: vnhw dsrc hsie ihzn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
  address: 0.0.0.0

aes:
  secret:
    key: sGvIcQnR7jP0sGvIcQnR7jP0sGvIcQnR